kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo 123456678

---
kind: pipeline
type: docker
name: test

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo 123456678
