kind: pipeline
type: docker
name: abc

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo 123456678

---
kind: pipeline
type: docker
name: default
depends_on: 
- abc

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo 123456678

